-- Climate Compass Supabase schema
-- Run this in Supabase SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.user_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  display_name text,
  location text,
  climate_focus text,
  bio text,
  total_events integer not null default 0,
  last_active_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.user_actions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  action_id text not null,
  is_selected boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (user_id, action_id)
);

create table if not exists public.user_topic_views (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  topic text not null check (topic in ('weather', 'oceans', 'food', 'health')),
  viewed_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.user_footprints (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  car_km numeric(10, 2) not null check (car_km >= 0),
  meat_meals numeric(10, 2) not null check (meat_meals >= 0),
  home_kwh numeric(10, 2) not null check (home_kwh >= 0),
  estimated_tco2e numeric(10, 2) not null check (estimated_tco2e >= 0),
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.user_quiz_attempts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  score smallint not null check (score between 0 and 3),
  answers jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.user_activity_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  event_type text not null,
  event_payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_user_actions_user_id on public.user_actions(user_id);
create index if not exists idx_user_topic_views_user_id on public.user_topic_views(user_id);
create index if not exists idx_user_footprints_user_id on public.user_footprints(user_id);
create index if not exists idx_user_quiz_attempts_user_id on public.user_quiz_attempts(user_id);
create index if not exists idx_user_activity_events_user_id on public.user_activity_events(user_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists set_user_profiles_updated_at on public.user_profiles;
create trigger set_user_profiles_updated_at
before update on public.user_profiles
for each row
execute procedure public.set_updated_at();

drop trigger if exists set_user_actions_updated_at on public.user_actions;
create trigger set_user_actions_updated_at
before update on public.user_actions
for each row
execute procedure public.set_updated_at();

create or replace function public.handle_new_user_profile()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.user_profiles (id, email, display_name)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'display_name', '')
  )
  on conflict (id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row
execute procedure public.handle_new_user_profile();

create or replace function public.bump_profile_activity()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.user_profiles
  set
    total_events = total_events + 1,
    last_active_at = new.created_at,
    updated_at = timezone('utc', now())
  where id = new.user_id;

  return new;
end;
$$;

drop trigger if exists on_activity_event_created on public.user_activity_events;
create trigger on_activity_event_created
after insert on public.user_activity_events
for each row
execute procedure public.bump_profile_activity();

alter table public.user_profiles enable row level security;
alter table public.user_actions enable row level security;
alter table public.user_topic_views enable row level security;
alter table public.user_footprints enable row level security;
alter table public.user_quiz_attempts enable row level security;
alter table public.user_activity_events enable row level security;

drop policy if exists "profiles_select_own" on public.user_profiles;
create policy "profiles_select_own"
on public.user_profiles
for select
using (auth.uid() = id);

drop policy if exists "profiles_insert_own" on public.user_profiles;
create policy "profiles_insert_own"
on public.user_profiles
for insert
with check (auth.uid() = id);

drop policy if exists "profiles_update_own" on public.user_profiles;
create policy "profiles_update_own"
on public.user_profiles
for update
using (auth.uid() = id)
with check (auth.uid() = id);

drop policy if exists "actions_crud_own" on public.user_actions;
create policy "actions_crud_own"
on public.user_actions
for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "topic_views_crud_own" on public.user_topic_views;
create policy "topic_views_crud_own"
on public.user_topic_views
for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "footprints_crud_own" on public.user_footprints;
create policy "footprints_crud_own"
on public.user_footprints
for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "quiz_attempts_crud_own" on public.user_quiz_attempts;
create policy "quiz_attempts_crud_own"
on public.user_quiz_attempts
for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "activity_events_crud_own" on public.user_activity_events;
create policy "activity_events_crud_own"
on public.user_activity_events
for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);
